# -*- coding: utf-8 -*-
"""Rock_paper_scissors .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hKl-9qAI60a4pjss9omkEPHArdnH8qQG
"""

import random 
user_wins = 0
bot_wins = 0
options = ["rock","paper","scissors"]
n = 0

while n < 3:
  user_input = input("Type your choice (Rock/Paper/Scissors), Or Q to quit: ").lower()
  if user_input == "q":
    break
  if user_input not in ["rock","paper","scissors"]:
    continue
  index = random.randint(0,2)
  print("Computer chose: '"+ options[index] +"'")

  if user_input == options[index]:
    print("***It's a Draw***")
  elif user_input == "rock" and index == 2:
    print("***You won!***")
    user_wins += 1
  elif user_input == "paper" and index == 0:
    print("***You won!***")
    user_wins += 1
  elif user_input == "scissors" and index == 1:
    print("***You won!***")
    user_wins += 1
  
  else:
    print("***You lost!***")
    bot_wins += 1
  n += 1

print(f"The User Won {user_wins} times")
print(f"The Computer Won {bot_wins} times")

if user_wins == bot_wins:
  print("!!! Draw !!!")
elif user_wins > bot_wins:
  print("___The User Has Won!___")
else:
  print("___Computer Has Won!___")