# -*- coding: utf-8 -*-
"""Guess the random number .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hKl-9qAI60a4pjss9omkEPHArdnH8qQG
"""

import random

nb = 0
min = 1
max = 100
number = random.randint(min,max)

while True:

  inputs = input(f"Guess the Number between ({min},{max})")
  if inputs.isdigit():
    guess = int(inputs)
    if guess > 100:
      print("Your input should be lower than 100")
      break
    else:
      nb += 1
      if guess < number:
        print(f"{guess} is Low")
      elif guess > number:
        print(f"{guess} is High")
      else:
        print(f"You guessed it write: {guess}")
        print(f"It took you {nb} guesses to get it right")
        break
  else:
    print("Your input should be a Number; Try again.")

